### ISSUE TITLE
Content-Type

### ISSUE THREAD

**Issue by mcordingley** [paragonie/sapient#11]
For encrypted bodies, should the "Content-Type" header refer to the plain-text or cipher-text? If the former, it's technically lying about the contents and leaking information. If the latter, then the "Content-Type" of the body should be safely stowed someplace for reinstatement upon decryption.

**Comment by paragonie-scott** [comment]
*proceeds to document this as an acceptable leak rather than deal with encrypting headers*

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/sapient/commit/47effd94c0213850c0ed6736f2fe8460e8e0dcfb

**Comment by mcordingley** [comment]
Works for me.
