### ISSUE TITLE
.NET Framework

### ISSUE THREAD

**Issue by developer-variety** [paragonie/sapient#12]
Do you believe that this toolkit would be able to be used in the .NET framework?

PHP as the server and the .NET Framework as the client.

**Comment by paragonie-scott** [comment]
Well, a .NET implementation would need to be written (i.e. using [libsodium-net](https://github.com/adamcaudill/libsodium-net)). But otherwise, yes, it's possible to build it for .NET.

**Comment by developer-variety** [comment]
Alright thanks I'll look into it.
