### ISSUE TITLE
Better Flexibility (not tied entirely to Guzzle) (Reported on Reddit instead of Github)

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/sapient#4]
https://www.reddit.com/r/PHP/comments/6inksq/paragoniesapient_secure_api_toolkit_for_php_7/

There are two concerns with moving away from Guzzle:

1. The `create*()` methods can't return an `Interface`, they have to return a `Request` or `Response` object, because they invoke `new _____()`. This is the technical concern.
2. If we make it totally pluggable, we risk allowing developers to choose HTTP clients that contain vulnerabilities and then we'll get blamed for vulnerabilities existing, especially in bug bounty reports. This is the non-technical concern.

Unless these clients provide a native `createRequest()` method, we'll have to continue returning Guzzle's.

**Comment by mcordingley** [comment]
[Line 575](https://github.com/paragonie/sapient/blob/master/src/Sapient.php#L575) on down can be moved off without triggering the technical concern. The `create*()` methods could remain coupled to Guzzle, since they're basically just convenience methods for creating Guzzle objects that have been passed through the other methods.

For concern 2, perhaps it could be addressed with a disclaimer that Guzzle is the only officially supported HTTP client and that bug bounties must be demonstrated using Guzzle to be accepted.

**Comment by mcordingley** [comment]
I'll tack on one other thing here. Suppose you're implementing this on an API server. Guzzle is a client library for HTTP, not a server library. The requests and responses handled by that server would go through a different library, such as something [Symfony](https://github.com/symfony/http-foundation)-derived. While properly implementing this would be the responsibility of the various frameworks, they'd need the raw tools to be able to do so without needing to use Guzzle. This is a thornier issue than what has been raised on Reddit, and I don't have any good ideas for how to approach it. 👎

**Comment by paragonie-scott** [comment]
Idea: Make a general interface, move `create*()` methods to an adapter that you can inject a Guzzle object into?

**Comment by mcordingley** [comment]
I see basically three different sets of code: primitives on static functions that other things build off of, generic objects that tie together the primitives and keys into useful operations for any sort of user, and HTTP client specific code that couples with Guzzle to create those handy factory methods and work directly with the Request and Response objects. There may also be a class or two specifically built for use in Guzzle middleware. Those first two items seem like they should be in a separate package that would be depended on by frameworks and by the package with the Guzzle components. I'd also introduce several interfaces.

I could submit a pull with these ideas better refined, but don't want to send a pull with heavy reorganization unsolicited.

**Comment by paragonie-scott** [comment]
I just committed a restructure. What do you think of the changes made thus far?

**Comment by mcordingley** [comment]
The interface is a 👍 .

For the `Sapient` class, it's OK in PHP to call static methods non-statically. It just raises a warning. You can probably kill off the magic method in the bottom of it. For classes like this where it's not intended to be used in an object context, I usually just define a private constructor to prevent stray instantiations from happening.

Still thinking about the rest.

**Comment by kelunik** [comment]
I wouldn't consider anything that throws a warning to be acceptable.

**Comment by paragonie-scott** [comment]
If people want to inject a Sapient instance (not sure why they would in this case, but hey, dependency injection is *in* these days), forcing static-only access might upset a lot of people.

The `__call()` isn't hurting anything.

**Comment by mcordingley** [comment]
Eh, whatever works for you. Don't want to end up bike-shedding. ;)

**Comment by paragonie-scott** [comment]
Heh, don't mistake my focus for anything it's not. I greatly appreciate the feedback. :)

**Comment by mcordingley** [comment]
It's looking as if the `Sapient` class now exists for other libraries to use, right? Aside from its constants, I'm not actually seeing it used elsewhere in here.

**Comment by paragonie-scott** [comment]
Yep, it's mostly for working with PSR-7 interfaces now.

**Comment by paragonie-scott** [comment]
I think #6 will clean up a lot of the design, make it flexible, and not explicitly require anything a particular HTTP library provides.
