### ISSUE TITLE
Stream Bodies

### ISSUE THREAD

**Issue by mcordingley** [paragonie/sapient#5]
PSR-7 [uses streams for bodies](http://www.php-fig.org/psr/psr-7/#streams), but the sodium primitives in use here (so far as I can tell) expect a whole string representation to work their magic. That's going to cause issues for large bodies.

Ideally, the code should be able to encrypt, decrypt, sign, verify, and authenticate streams without having the whole stream in memory at once. I'm sure this complicates matters greatly, but is a boon when dealing with large bodies. Without this, there will exist a class of requests and responses that cannot be secured by Sapient.

For reference, see [PSR-7's](https://github.com/php-fig/http-message/blob/master/src/StreamInterface.php) `StreamInterface`, how Guzzle implements it, and Symfony's `StreamedResponse` class for returning streams to the client.

**Comment by paragonie-scott** [comment]
> That's going to cause issues for large bodies.

PHP 7 has bigint support, so as long as the target system has enough RAM, it won't be an issue.

**Comment by mcordingley** [comment]
In my particular case "large" means gigabytes, which is why it's streamed instead of put into memory all at once. It's handling the case where the API returns a file instead of something small like JSON. This may be a bit too much of an edge case for the library to handle. I just want streams to be explicitly included in or discarded from scope instead of overlooked.

**Comment by paragonie-scott** [comment]
The only use-case I can see here would be to create a different method that uses [Sodium_Compat_File](https://github.com/paragonie/sodium_compat/blob/master/src/File.php) but with resources instead of filenames.

That sounds tricky. I'd feel safer just documenting that this operates on strings in-memory and leaving it at that.

**Comment by mcordingley** [comment]
I've been thinking about this, and we've got something of an insurmountable problem to this:

- The MAC goes in a header.
- Headers must go out before the body.
- The MAC needs the whole of the body before it can be calculated.
